### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by darkestfloyd** [NischalBhatewara/PNet#1]
Leave a comment with links to papers you think are relevant, with a small abstract for context.

**Comment by darkestfloyd** [comment]
A good [blog post](https://blog.insightdatascience.com/how-to-solve-90-of-nlp-problems-a-step-by-step-guide-fda605278e4e) on NLP problems, may help in future. Mentioning for documentation purposes.

**Comment by NischalBhatewara** [comment]
Paper: [Learning to Generate Pseudo-code from Source Code using Statistical Machine Translation.](http://www.phontron.com/paper/oda15ase.pdf)
The paper describes a SMT based technique to generate pseudo-code from source code. The results of the paper are not very promising though.

**Comment by varun-sundar-rabindranath** [comment]
[From Natural Language Specifications to Program Input Parsers](http://people.csail.mit.edu/fanl/papers/acl2013.pdf)  

The paper discusses techniques to automatically generate input parser code, that given a specification  (as commonly found in programming platforms), generates code to parse the input as per the specification

**Comment by varun-sundar-rabindranath** [comment]
[Using Semantic Unification to Generate Regular Expressions from Natural Language](https://people.csail.mit.edu/regina/my_papers/reg13.pdf)

The paper discusses techniques to convert natural language to regular expressions

**Comment by varun-sundar-rabindranath** [comment]
[Base Paper - A Syntactic Neural Model for General-Purpose Code Generation
](https://arxiv.org/abs/1704.01696)

This paper discusses techniques to convert natural language descriptions (comments found in source code) to Python programs. 

GitHub link: [pcyin/NL2code](https://github.com/pcyin/NL2code)

**Comment by varun-sundar-rabindranath** [comment]
[Abstract Syntax Networks for Code Generation and Semantic Parsing](https://arxiv.org/abs/1704.07535)

This paper is similar to the [base paper](https://arxiv.org/abs/1704.01696), and confirms the results of the base paper. Though the goals are similar between the papers, the latter has tackled problems a little differently.

**Comment by krishnakaranam3732** [comment]
[A paper using semantic parsers for converting natural language to code on IFTTT dataset](http://www.cs.utexas.edu/~ai-lab/downloadPublication.php?filename=http://www.cs.utexas.edu/users/ml/papers/quirk.acl15.pdf&pubid=127514)

This paper uses program retrieval, machine translation and generation without alignment to map the natural language descriptions to program representations if IFTTT recipes.

**Comment by darkestfloyd** [comment]
[Incorporating Copying Mechanism in Sequence-to-Sequence Learning](https://arxiv.org/abs/1603.06393)

The paper describes a CopyNet - a Seq2Seq network with some modification to add the ability of copying text from the input to the output. This could help copy variable names from the input. Although the [base paper](https://arxiv.org/abs/1704.01696) handles this internally, we could use the technique described here if we see that the network is not able to copy variable names from the input.

**Comment by darkestfloyd** [comment]
Base papers and data selected. Moving on to #5
