### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by darkestfloyd** [NischalBhatewara/PNet#3]
Look for potential data to be used for training.

**Comment by darkestfloyd** [comment]
Paper: [Learning to Generate Pseudo-code from Source Code using Statistical Machine Translation.](http://www.phontron.com/paper/oda15ase.pdf)
The paper describes a SMT based technique to generate pseudo-code from source code. The results of the paper are not very promising though. We could potentially use it to generate more data for training.

**Comment by darkestfloyd** [comment]
Paper: [A parallel corpus of Python functions and documentation strings for automated code documentation and code generation](https://arxiv.org/abs/1707.02275)
Like the previous paper, this paper describes ways to generate docstring from source code.

**Comment by varun-sundar-rabindranath** [comment]
https://github.com/EdinburghNLP/code-docstring-corpus

Python - Comments opensource dataset
